### ISSUE TITLE
How do I use the pytest_twisted.inlineCallbacks decorator in conjunction with fixtures?

### ISSUE THREAD

**Issue by FRiMN** [pytest-dev/pytest-twisted#105]
How can I pass the necessary fixtures to the decorator or to the function to be decorated?

With this code:
``` python
class TestScrapingSite(TestCase):
    @pytest_twisted.inlineCallbacks
    def test_crawler_stats(self, caplog):
        yield 1
```
raised error
```
TypeError: test_crawler_stats() missing 1 required positional argument: 'caplog'
```

**Comment by altendky** [comment]
I'm not sure pytest-twisted supports decorating methods.  Maybe it should.  What is `TestCase`?

**Comment by altendky** [comment]
I'll go ahead and guess it's just straight [unittest.Testcase](https://docs.python.org/3/library/unittest.html#unittest.TestCase).  Do you really need to be using `unittest` in pytest tests?  I'm suspecting that's the easy solution for you.  Just go all in with pytest where you mostly don't use classes for tests.  But, I will also think over whether it makes sense to add support for this.

**Comment by FRiMN** [comment]
> I'm not sure pytest-twisted supports decorating methods. Maybe it should. What is `TestCase`?

`TestCase` it is base class from `unittest`.

In documentation saing:
> Using twisted.internet.defer.inlineCallbacks as a decorator for test functions, which use fixtures, does not work. Please use pytest_twisted.inlineCallbacks instead.

**Comment by FRiMN** [comment]
> I'll go ahead and guess it's just straight [unittest.Testcase](https://docs.python.org/3/library/unittest.html#unittest.TestCase). Do you really need to be using `unittest` in pytest tests? I'm suspecting that's the easy solution for you. Just go all in with pytest where you mostly don't use classes for tests. But, I will also think over whether it makes sense to add support for this.

Thanks. 

I am trying to repeat the code from https://github.com/scrapy/scrapy/blob/master/tests/test_closespider.py

But, if I take out a certain code in fixtures, perhaps I will be able to remake the test into a function.

**Comment by altendky** [comment]
Yes, `@pytest_twisted.inlineCallbacks` does work with fixtures.  I think the not-working part is applying this to a method rather than a function.  I rarely see classes in pytest tests but...  complete support is a good thing so this may still get implemented.  Note that applying to a unittest test case class is an additional layer away from 'normal' usage.

If you want to match that you would be using trial (part of twisted) instead of pytest and unittest.  If you want to use pytest but implement the same stuff you would generally not have a class and would put the setup and teardown into a [fixture with a `yield`](https://docs.pytest.org/en/latest/fixture.html#fixture-finalization-executing-teardown-code).

https://docs.pytest.org/en/latest/getting-started.html#group-multiple-tests-in-a-class

**Comment by altendky** [comment]
So while we were missing tests for methods, they are working as shown in #106 (the Windows Qt5 test failures were pre-existing and are being worked on in #104).  If nothing else we get improved test coverage out of this.  :]  While pytest can be used as a runner for unittest tests, I'm not sure it makes sense to have pytest-twisted work on unittest tests.  Rather that tests should be either unittest style or pytest style, even though you can mix the pytest runner with unittest tests.  If you have a counter argument I'd be glad to hear it.

Also, let me know where you get with a pure pytest/pytest-twisted approach.

**Comment by FRiMN** [comment]
Thanks.

I rewrited my tests following you comments. And it worked.
But I have another unexpected and strange behaviour. `caplog` fixture don't record all logs.

I think, I can close this issue.

**Comment by cdunklau** [comment]
Most of the pytest goodies won’t work at all with unittest. There are a few exceptions, but I would be quite surprised if any of those would work related to anything pytest-twisted. You might try some of the things here: https://docs.pytest.org/en/latest/unittest.html ...but it’s almost certainly more trouble than it’s worth. Pytest’s support for unittest definitely seems to be intended purely to support gradual migration from unittest to pytest, instead of a more comprehensive “mixing” approach.
