### ISSUE TITLE
Stop putting stuff in the pytest namespace

### ISSUE THREAD

**Issue by altendky** [pytest-dev/pytest-twisted#41]
I personally dislike the use of the pytest namespace as a place to collapse other namespaces.  `@pytest_twisted.inlineCallbacks` seems perfectly fine instead of `@pytest.inlineCallbacks`.  Presently #34 is adding two more items to `pytest_namespace()` for consistency, but I'd like to consider not adding those and also deprecating the existing `pytest.inlineCallbacks` and `pytest.blockon`.  Or at least deciding if we will or won't add anything more.

**Comment by altendky** [comment]
@meejah, after https://github.com/pytest-dev/pytest-twisted/issues/54#issuecomment-454263074 maybe you want to weigh in here as well about your preference.

**Comment by meejah** [comment]
I don't really mind either way, but it seemed "pretty common" to use `pytest.*` for stuff, even from plugins, which is why I'm currently using `pytest.inlineCallbacks`. That said, I recall thinking this was a little weird/magic (as that stuff just "isn't there" if you don't have `pytest_twisted` and that probably makes it harder to debug for others).

Being explicit with `from pytest_twisted import inlineCallbacks` or so does seem like a better, more-sustainable and more-debuggable/discoverable way to use plugin-provided functions/objects.

**Comment by nicoddemus** [comment]
> Being explicit with from pytest_twisted import inlineCallbacks or so does seem like a better, more-sustainable and more-debuggable/discoverable way to use plugin-provided functions/objects.

Indeed that is one of the reasons why we deprecated and then removed that hook. An `AttributeError` exception in the `pytest.inlineCallbacks` doesn't help the user at all to figure out that they need the `pytest-twisted` plugin. 👍

**Comment by nicoddemus** [comment]
@altendky one way to deprecate this is to install a slightly different version of the `inlineCallbacks` decorator that issues a `DeprecationWarning` into the `pytest` namespace, while providing a new function (perhaps even using a new name if you want) that should be imported directly from `pytest_twisted` that does not issue the warning.

**Comment by altendky** [comment]
Thanks for the comments.  Implementing deprecation in #58.
